const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: 'https://static01.nyt.com/images/2016/06/15/dining/15PANCAKEGUIDE3-WEB/15PANCAKEGUIDE3-WEB-articleLarge.jpg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: 'https://media.istockphoto.com/photos/double-burgers-at-diner-picture-id1268633498?k=20&m=1268633498&s=612x612&w=0&h=qOtvSq_MyLERajoYtPeEeYznYPUVeM1p8rbuk1GFKPg=  ',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: 'https://bakingmischief.com/wp-content/uploads/2019/07/chocolate-milkshake-square.jpg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: 'https://media-exp1.licdn.com/dms/image/C5612AQFZ24FP-EV1rg/article-inline_image-shrink_1500_2232/0/1620578564594?e=2147483647&v=beta&t=iuh6dvj8bbjEgYEYsF2is-rlpb_QtFVpreL7MWi0EUw',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: 'https://static.toiimg.com/photo/msid-68393465/68393465.jpg?1602991',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: 'https://topsecretrecipes.com/images/product/cheesecake-factory-oreo-dream-extreme-cheesecake-copycat-recipe.jpg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: 'https://www.simplyrecipes.com/thmb/e-9WIsIF8XCP3u_nKxLY8Oib6Z0=/2000x1125/smart/filters:no_upscale()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2019__03__Candied-Bacon-LEAD-01-fc5c426ec29d4a24b88c7f0f4647fd09.jpg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: 'https://previews.123rf.com/images/belchonock/belchonock1802/belchonock180263053/95685955-pranzo-americano-tradizionale-da-vicino.jpg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: 'https://static.toiimg.com/photo/msid-71067021/71067021.jpg?739619',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
